### ISSUE TITLE
Several errors in the log

### ISSUE THREAD

**Issue by Krocko** [ekutner/home-connect-hass#3] opened 2022-02-12 03:12 UTC
I see the following errors in the Home Assistant log:
[home-assistant (1).log.txt](https://github.com/ekutner/home-connect-hass/files/8052611/home-assistant.1.log.txt)

**Comment by Krocko** [comment] 2022-02-12 08:00
Some more errors. 
[home-assistant (2).log.txt](https://github.com/ekutner/home-connect-hass/files/8053023/home-assistant.2.log.txt)

**Comment by ekutner** [comment] 2022-02-12 15:29
It seems there there was some problem loading cached data which then cascaded into other issues.
Please remove the integration, then update to the latest version (make sure you get v0.2.6) then restart HA an then add the integration back again. This should give us a clean start.

It seems that you've already done this but please make sure you have logging enabled in your config:
```
logger:
  default: info
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug
```
If you still see issues then please upload the log again. Thank you and sorry for the back and forth, I keep discovering edge cases where the API is not behaving as documented and I have to add special handling.

**Comment by Krocko** [comment] 2022-02-12 15:55
I have done this. 
Only the CoffeeMaker is discovered and the WasherDryer is missing. 
After a restart from ha, the most entities from the CoffeeMaker are unavailable. And the same errors in the log.

**Comment by ekutner** [comment] 2022-02-12 16:28
Please press the *Home Connect Refresh* button and upload the entire log from when you pressed for about 2 minutes.
Also, please specify what is the *Home Connect Status* sensor value

**Comment by Krocko** [comment] 2022-02-12 16:59
The state of the status sensor is loading. 
Will test and upload the log tomorrow.

**Comment by ekutner** [comment] 2022-02-12 22:13
State "LOADING" means the integration didn't finish loading the state data from the Home Connect service. The only "good" reason for that to happen is if you clicked the "refresh" button many times. That creates a lot of requests to the service which then goes into a defensive mode and blocks additional calls for up to 24 hours.
If when you check tomorrow the state didn't change to either READY or LOADING_FAILED then please update to v0.2.7 which include additional logging and upload a fresh and complete log.
Since I can't reproduce any of these issues on my washing machine I have to guess and try to figure out things from the logs, so really appreciate your help with it.

**Comment by Krocko** [comment] 2022-02-13 08:27
I generated a new app in the home connect developer portal. After several restarts of home assistant and a push on the reload button, I have both devices in home assistant. The CoffeeMaker is working. Will test the WasherDryer later. I think there is same adjustment in the naming of the entities necessary.
Also the Finish In Relative option should be in hours:minutes and not in seconds. The corresponding sensor show this in the right format. 
For the WasherDryer I have no option to choose between washing, drying and washing&drying. See the screenshot below.
If you need more information please tell me.
I also have postman installed and have the api imported.

![image](https://user-images.githubusercontent.com/29394115/153745123-f985d6db-99e7-438b-8670-bd256007e092.png)
![image](https://user-images.githubusercontent.com/29394115/153745130-7603439d-c004-44fe-97d7-caaadaa87f4c.png)
![image](https://user-images.githubusercontent.com/29394115/153745132-a3fcb31e-a427-4926-bf74-7d162bb62c52.png)
![image](https://user-images.githubusercontent.com/29394115/153745138-008aa5fe-00b5-4315-a851-b51c3b603607.png)
![image](https://user-images.githubusercontent.com/29394115/153745141-ff041d8a-f2dc-460e-9365-4e9e43783a77.png)
![image](https://user-images.githubusercontent.com/29394115/153745156-c5f0e702-3e30-414a-ae9c-6c9015b225b6.png)
![image](https://user-images.githubusercontent.com/29394115/153745173-604eb257-e79f-4264-b2c7-397599778e40.png)
![image](https://user-images.githubusercontent.com/29394115/153745179-743cd38f-6dfa-40ae-ba4c-feaed15492d6.png)
![image](https://user-images.githubusercontent.com/29394115/153745182-b8c0fb2e-909f-4035-9c6b-26aabb7cdf18.png)

**Comment by ekutner** [comment] 2022-02-13 11:41
Please update to build 0.2.9
I've "fixed" the first two exceptions from the log (fixed in the sense that it will handle the invalid server state gracefully).
The last error is because the device was offline.
There are two other errors that I don't understand and need additional info about. The one with the  LaundryCare.Washer.Option.SpinSpeed having invalid value and the BSH.Common.Option.FinishInRelative being not selectable. 

In order to understand these issues better I've added a new button  *Home Connect Debug*. Press it once then please upload the full logfile called home-assistant.log from your config folder.

**Comment by Krocko** [comment] 2022-02-13 11:43
Ist it possible to send you the full log in private?
Are you on discord?

**Comment by ekutner** [comment] 2022-02-13 12:40
Sure and yes, I'm on discord, my user is ekutner.

**Closed** 2022-02-16 10:19 UTC
