### ISSUE TITLE
Failed to get a valid response from Home Connect server

### ISSUE THREAD

**Issue by rooneyaut** [ekutner/home-connect-hass#243] opened 2023-08-30 16:25 UTC
## Describe the bug
From one day to another the integration stopped working.
I've waited few days and tried to readd the integration to Home Assistant again, but the error is still the same.

## Version of the custom_component
0.6.3

## Configuration

```yaml
home_connect_alt:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret
  language: de
```

## Debug log

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
    response = await self._api.async_get('/api/homeappliances')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/home_connect_async/api.py", line 118, in async_get
    return await self._async_request('GET', endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/home_connect_async/api.py", line 113, in _async_request
    raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)

```
## Log file
[home-assistant.log](https://github.com/ekutner/home-connect-hass/files/12478052/home-assistant.log)

**Comment by StevenBoelhouwer** [comment] 2023-09-02 10:49
Experiencing the same issue here. Same log statements as well

**Comment by jansemrad** [comment] 2023-09-05 05:29
Same issue by me.

**Comment by disruptivepatternmaterial** [comment] 2023-09-08 18:44
Has anyone been able to get this to work again? If so what steps did you take?

**Comment by Neunsen** [comment] 2023-09-11 10:50
Getting this since yesterday: fetch https://api.home-connect.com/api/homeappliances/events failed: 401
The Home Connect App shows an error with the server connection as well.

**Comment by ekutner** [comment] 2023-09-12 13:27
Duplicate of #215

**Closed by ekutner** 2023-09-12 13:27 UTC
Labels: duplicate
