### ISSUE TITLE
Alarmclock

### ISSUE THREAD

**Issue by BrukerJan** [ekutner/home-connect-hass#299] opened 2023-12-06 16:22 UTC
## Describe the bug
Alarm clock does not count down correctly

When setting the alarm clock on a 'Bosch oven' the number.bosch_oven and the sensor.bosch_oven shows the correct number of seconds. However, the sensor does not count down according to the oven alarm clock which I suppose it should do. Additionally, when the oven alarm clock has counted down, it takes about 2 minutes before the number.bosch_oven and sensor.bosch_oven are set to 0 socnds.

## Version of the custom_component
1.0.0

## Configuration
None

## Debug log
Attached

```text
Paste the exception info here or attach the full log file

```
[home-assistant_home_connect_alt_2023-12-06T16-22-09.171Z.log](https://github.com/ekutner/home-connect-hass/files/13588581/home-assistant_home_connect_alt_2023-12-06T16-22-09.171Z.log)

**Comment by ekutner** [comment] 2023-12-06 16:38
The integration is updated based on events received from the Home Connect API, the frequency and timeliness of these updates are controlled by the API.

duplicate of #239

**Closed by ekutner** 2023-12-06 16:38 UTC
