### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Asdrubale1234** [ekutner/home-connect-hass#212] opened 2023-04-29 16:46 UTC
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.home_connect_alt
Source: /config/custom_components/home_connect_alt/__init__.py:132 
Integration: Home Connect Alt (documentation, issues) 
First occurred: 18:43:46 (1 occurrences) 
Last logged: 18:43:46

Failed to load data for the HomeConnect object
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/homeconnect.py", line 139, in async_load_data
    response = await self._api.async_get('/api/homeappliances')
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 118, in async_get
    return await self._async_request('GET', endpoint)
  File "/usr/local/lib/python3.10/site-packages/home_connect_async/api.py", line 113, in _async_request
    raise HomeConnectError("Failed to get a valid response from Home Connect server", 902)
home_connect_async.common.HomeConnectError: ('Failed to get a valid response from Home Connect server', 902, None, None, None)

**Comment by ekutner** [comment] 2023-05-04 19:16
Duplicate of #215

**Closed** 2023-05-04 19:16 UTC
