### ISSUE TITLE
Catch the alarm signal from 'BSH.Common.Setting.AlarmClock'

### ISSUE THREAD

**Issue by liouma** [ekutner/home-connect-hass#312] opened 2024-01-09 18:14 UTC
**Is your feature request related to a problem? Please describe.**
I use your integration with a SIEMENS oven. When the alarm of my oven is triggered, my automation is triggered a long long time later by sensor.myoven_alarmclock.

**Describe the solution you'd like**
The following integration work fine. The alarm is triggered instantely. Unfortunately it is not an integration for HA but for Jeedom:
https://github.com/jmvedrine/homeconnect/
I'm not an expert, but having a look at the code, it seems to be triggered by :
'BSH.Common.Setting.AlarmClock

As the alarm is probably the most usefull and common feature, I'm sure you'll have a look at it and you will find a way to make your integration as efficient as this french guy did.

**Comment by ekutner** [comment] 2024-01-15 16:45
This is a duplicate of #239 which you yourself have opened. As I noted in the other issue this integration is using events received from the HC API to trigger HA events, if an event is not received from the API in time then it won't be published. This behavior is not going to change and if you feel that there is a problem with events not being received on time you should report it to HC so they can fix it on their end.

**Closed** 2024-01-15 16:45 UTC

**Comment by liouma** [comment] 2024-01-16 17:57
Not a duplicate as I think I give you the solution. You don't care. Ok. 
I will just uninstall this integration and let know that it is useless..

**Comment by dennypage** [comment] 2024-01-16 18:34
@liouma Dude. This is no way to speak to a volunteer.

**Comment by liouma** [comment] 2024-01-17 04:17
Volonteer for what? you don't care about my messages. I really tried to explain you my point but you don't care.
Without the one usefull feature for an oven : catching the alarm, your integration is useless.
Really useless.
Sorry you refused to understand.

**Comment by dennypage** [comment] 2024-01-17 06:18
> Volonteer for what? you don't care about my messages. I really tried to explain you my point but you don't care. Without the one and only usefull feature for an oven : catching the alarm, your integration is useless.
> ...
> Volonteer for what, for who? certainly not for users like me. Really useless. Not functional, USELESS. I spent time to try to explain the problem but you don't seem to care. I even looked at the code of a working integration to try to point you the solution, but you did not even look at it. I'm really sorry that you refused to understand.

Wow. Please accept my apologies, but I view this as a horrible, and very short sighted, response.

To be clear, I am not the maintainer of this integration (@ekutner). I am just another user of the integration who happened to see your comments.

By volunteer, I mean that @ekutner is a volunteer in providing and maintaining this integration. He does this out of the kindness of his heart.

Your abrasive attitude and flagrant disrespect will win no one to your position. If you want to succeed in the open source world, you need to work with polite words and respect rather than with bile. And if the project owner doesn't agree with your position following polite discourse, then you need to accept that and move on. If that just doesn't work for you, then I commend you to stop using open source.

**Comment by liouma** [comment] 2024-01-17 07:47
Please check the history before taking position.
