### ISSUE TITLE
dishwasher relaxant / salt low level warning ?

### ISSUE THREAD

**Issue by gibman** [ekutner/home-connect-hass#129] opened 2022-11-01 21:13 UTC
From time to time I receive a notification ony my siemens home connect app telling me that salt and/or relaxant levels on my dishwasher are low thus need refilling.

it would be great id these could be exposed as a binary sensor in home assistant.
is this part of the home connect api ?

**Comment by ekutner** [comment] 2022-11-02 15:32
Duplicate of #53

**Closed by ekutner** 2022-11-02 15:32 UTC

**Comment by ekutner** [comment] 2022-11-02 15:35
duplicate of #115
