### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by vandersson888** [ekutner/home-connect-hass#100] opened 2022-08-28 07:26 UTC
## Configuration

```yaml

Add your configuration here.

```

## Debug log

```text
Add your logs here (or attach the log file).

Logger: homeassistant.components.number
Source: components/number/__init__.py:119 
Integration: Number (documentation, issues) 
First occurred: 09:21:46 (2 occurrences) 
Last logged: 09:21:46

custom_components.home_connect_alt.number::OptionNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.home_connect_alt.number::SettingsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

```

**Comment by ekutner** [comment] 2022-08-28 20:58
Duplicate of #77

**Closed by ekutner** 2022-08-28 20:58 UTC
Labels: duplicate
